
USE `mysql`;
UPDATE USER SET `host`='%' WHERE USER='root' and `host`='localhost';
FLUSH PRIVILEGES;

CREATE DATABASE IF NOT EXISTS `coreos`;

USE `coreos`;


DROP TABLE IF EXISTS `bld_fat`;

CREATE TABLE IF NOT EXISTS  `bld_fat` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `userid` INT(11) DEFAULT NULL COMMENT '用户ID',
  `username` VARCHAR(100) DEFAULT NULL COMMENT '用户名',
  `zfhl` VARCHAR(100) DEFAULT NULL COMMENT '脂肪含量',
  `bmi` VARCHAR(100) DEFAULT NULL COMMENT 'bmi',
  `jcdx` VARCHAR(100) DEFAULT NULL COMMENT '基础代谢',
  `tzpd` VARCHAR(100) DEFAULT NULL COMMENT '体质判定',
  `txpd` VARCHAR(100) DEFAULT NULL COMMENT '体型判定',
  `time` VARCHAR(100) DEFAULT NULL COMMENT '测量时间',
  `alert` VARCHAR(100) DEFAULT NULL COMMENT '报警',
  `ysjy` VARCHAR(1024) DEFAULT NULL COMMENT '医生建议',
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=40 DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `bld_oxygen`;

CREATE TABLE IF NOT EXISTS  `bld_oxygen` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `userid` INT(11) DEFAULT NULL COMMENT '用户ID',
  `username` VARCHAR(100) DEFAULT NULL COMMENT '用户名',
  `zfhl` VARCHAR(100) DEFAULT NULL COMMENT '脂肪含量',
  `bmi` VARCHAR(100) DEFAULT NULL COMMENT 'bmi',
  `jcdx` VARCHAR(100) DEFAULT NULL COMMENT '基础代谢',
  `tzpd` VARCHAR(100) DEFAULT NULL COMMENT '体质判定',
  `txpd` VARCHAR(100) DEFAULT NULL COMMENT '体型判定',
  `time` VARCHAR(100) DEFAULT NULL COMMENT '测量时间',
  `alert` VARCHAR(100) DEFAULT NULL COMMENT '报警',
  `ysjy` VARCHAR(1024) DEFAULT NULL COMMENT '医生建议',
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=25 DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `bld_press`;

CREATE TABLE IF NOT EXISTS  `bld_press` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `userid` INT(11) DEFAULT NULL COMMENT '用户ID',
  `username` VARCHAR(100) DEFAULT NULL COMMENT '用户名',
  `zfhl` VARCHAR(100) DEFAULT NULL COMMENT '脂肪含量',
  `bmi` VARCHAR(100) DEFAULT NULL COMMENT 'bmi',
  `jcdx` VARCHAR(100) DEFAULT NULL COMMENT '基础代谢',
  `tzpd` VARCHAR(100) DEFAULT NULL COMMENT '体质判定',
  `txpd` VARCHAR(100) DEFAULT NULL COMMENT '体型判定',
  `time` VARCHAR(100) DEFAULT NULL COMMENT '测量时间',
  `alert` VARCHAR(100) DEFAULT NULL COMMENT '报警',
  `ysjy` VARCHAR(1024) DEFAULT NULL COMMENT '医生建议',
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=25 DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `bld_sugar`;

CREATE TABLE IF NOT EXISTS  `bld_sugar` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `userid` INT(11) DEFAULT NULL COMMENT '用户ID',
  `username` VARCHAR(100) DEFAULT NULL COMMENT '用户名',
  `zfhl` VARCHAR(100) DEFAULT NULL COMMENT '脂肪含量',
  `bmi` VARCHAR(100) DEFAULT NULL COMMENT 'bmi',
  `jcdx` VARCHAR(100) DEFAULT NULL COMMENT '基础代谢',
  `tzpd` VARCHAR(100) DEFAULT NULL COMMENT '体质判定',
  `txpd` VARCHAR(100) DEFAULT NULL COMMENT '体型判定',
  `time` VARCHAR(100) DEFAULT NULL COMMENT '测量时间',
  `alert` VARCHAR(100) DEFAULT NULL COMMENT '报警',
  `ysjy` VARCHAR(1024) DEFAULT NULL COMMENT '医生建议',
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=25 DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `fk_user_mn`;

CREATE TABLE IF NOT EXISTS  `fk_user_mn` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `userid` INT(11) DEFAULT NULL,
  `fkid` INT(11) DEFAULT NULL,
  `type` VARCHAR(100) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=66 DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `log`;

CREATE TABLE IF NOT EXISTS  `log` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `level` VARCHAR(10) DEFAULT NULL,
  `userid` INT(11) DEFAULT NULL,
  `username` VARCHAR(100) DEFAULT NULL,
  `msg` VARCHAR(1024) DEFAULT NULL,
  `time` VARCHAR(40) DEFAULT NULL,
  `ip` VARCHAR(100) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=2758 DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `mn_doctor`;

CREATE TABLE IF NOT EXISTS  `mn_doctor` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `name` VARCHAR(100) DEFAULT NULL COMMENT '姓名',
  `phone` VARCHAR(100) DEFAULT NULL COMMENT '电话',
  `address` VARCHAR(100) DEFAULT NULL COMMENT '住址',
  `ill` VARCHAR(100) DEFAULT NULL COMMENT '主治',
  `age` VARCHAR(100) DEFAULT NULL COMMENT '年龄',
  `hospital` VARCHAR(100) DEFAULT NULL COMMENT '医院',
  `years` VARCHAR(100) DEFAULT NULL COMMENT '经验',
  `time` VARCHAR(100) DEFAULT NULL COMMENT '录入时间',
  `sex` VARCHAR(100) DEFAULT NULL COMMENT '性别',
  `city` VARCHAR(100) DEFAULT NULL COMMENT '城市',
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=19 DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `mn_info`;

CREATE TABLE IF NOT EXISTS  `mn_info` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `name` VARCHAR(100) DEFAULT NULL COMMENT '姓名',
  `age` VARCHAR(100) DEFAULT NULL COMMENT '年龄',
  `city` VARCHAR(100) DEFAULT NULL COMMENT '城市',
  `address` VARCHAR(100) DEFAULT NULL COMMENT '详细地址',
  `phone` VARCHAR(100) DEFAULT NULL COMMENT '电话',
  `ill` VARCHAR(100) DEFAULT NULL COMMENT '病史',
  `profession` VARCHAR(100) DEFAULT NULL COMMENT '工作',
  `sex` VARCHAR(100) DEFAULT NULL COMMENT '性别',
  `time` VARCHAR(100) DEFAULT NULL COMMENT '创建时间',
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `mn_relatives`;

CREATE TABLE IF NOT EXISTS  `mn_relatives` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `name` VARCHAR(100) DEFAULT NULL COMMENT '姓名',
  `age` VARCHAR(100) DEFAULT NULL COMMENT '年龄',
  `address` VARCHAR(100) DEFAULT NULL COMMENT '详细住址',
  `relatives` VARCHAR(100) DEFAULT NULL COMMENT '关系',
  `phone` VARCHAR(100) DEFAULT NULL COMMENT '电话',
  `city` VARCHAR(100) DEFAULT NULL COMMENT '所在城市',
  `profession` VARCHAR(100) DEFAULT NULL COMMENT '工作',
  `sex` VARCHAR(100) DEFAULT NULL COMMENT '性别',
  `time` VARCHAR(100) DEFAULT NULL COMMENT '创建时间',
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `mn_volunteer`;

CREATE TABLE IF NOT EXISTS  `mn_volunteer` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `name` VARCHAR(100) DEFAULT NULL COMMENT '姓名',
  `age` VARCHAR(100) DEFAULT NULL COMMENT '年龄',
  `address` VARCHAR(100) DEFAULT NULL COMMENT '详细地址',
  `city` VARCHAR(100) DEFAULT NULL COMMENT '城市',
  `school` VARCHAR(100) DEFAULT NULL COMMENT '学校',
  `grade` VARCHAR(100) DEFAULT NULL COMMENT '年级',
  `sex` VARCHAR(100) DEFAULT NULL COMMENT '性别',
  `time` VARCHAR(100) DEFAULT NULL COMMENT '创建时间',
  `phone` VARCHAR(100) DEFAULT NULL COMMENT '电话',
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `user`;

CREATE TABLE IF NOT EXISTS  `user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `password` VARCHAR(100) DEFAULT NULL,
  `username` VARCHAR(100) DEFAULT NULL,
  `email` VARCHAR(100) DEFAULT NULL,
  `role` VARCHAR(100) DEFAULT NULL,
  `time` VARCHAR(100) DEFAULT NULL,
  `realname` VARCHAR(100) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8;

INSERT INTO `user` (`id`, `password`, `username`, `email`, `role`, `time`, `realname`) VALUES('1','admin','admin','1607646162@qq.com','admin','2017-04-12 17:25:12','admin');
INSERT INTO `mn_info` (`id`, `name`, `age`, `city`, `address`, `phone`, `ill`, `profession`, `sex`, `time`) VALUES('1','admin','18','北京','北京朝阳区','15931096058','无','全栈工程师','男','2017-04-13 14:12:13');
INSERT INTO `fk_user_mn` (`id`, `userid`, `fkid`, `type`) VALUES('1','1','1','mn_info');